version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus_graphql
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - net
    depends_on:
      - app
  grafana:
    image: grafana/grafana
    container_name: grafana
    env_file:
      - ./docker/grafana.env
    ports:
      - "3000:3000"
    networks:
      - net
  app:
  # build and start spring application inside a separate container using the same network as prometheus
    build: .
    ports:
      - "10015:10015"
    networks:
      - net
networks:
  net:
